# GreenForked Helm Chart - Base Values
# This file contains all configurable parameters with sensible defaults
# Environment-specific values files should override these defaults

global:
  environment: production
  imageRegistry: docker.io
  imageRepository: sharanggupta/greenforked
  imageTag: latest
  imagePullPolicy: IfNotPresent

namespace:
  create: true
  name: greenforked

ingress:
  enabled: false
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: greenforked.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 3000
        - path: /user
          pathType: Prefix
          service: user-service
          port: 8081
        - path: /recipe
          pathType: Prefix
          service: recipe-service
          port: 8082
        - path: /interaction
          pathType: Prefix
          service: interaction-service
          port: 8083
        - path: /category
          pathType: Prefix
          service: category-service
          port: 8084
  tls:
    - secretName: greenforked-tls
      hosts:
        - greenforked.local

nodePort:
  enabled: true
  frontend:
    port: 30300
  userService:
    port: 30081
  recipeService:
    port: 30082
  interactionService:
    port: 30083
  categoryService:
    port: 30084

db:
  postgres:
    enabled: true
    image: postgres:15
    port: 5432
    db: greenforked
    user: greenforked
    password: greenforked123
    persistence:
      size: 10Gi

services:
  userService:
    enabled: true
    replicaCount: 1
    port: 8081
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8081
      initialDelaySeconds: 120
      periodSeconds: 60
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8081
      initialDelaySeconds: 60
      periodSeconds: 30

  recipeService:
    enabled: true
    replicaCount: 1
    port: 8082
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8082
      initialDelaySeconds: 120
      periodSeconds: 60
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8082
      initialDelaySeconds: 60
      periodSeconds: 30

  interactionService:
    enabled: true
    replicaCount: 1
    port: 8083
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8083
      initialDelaySeconds: 120
      periodSeconds: 60
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8083
      initialDelaySeconds: 60
      periodSeconds: 30

  categoryService:
    enabled: true
    replicaCount: 1
    port: 8084
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8084
      initialDelaySeconds: 120
      periodSeconds: 60
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8084
      initialDelaySeconds: 60
      periodSeconds: 30

frontend:
  enabled: true
  replicaCount: 1
  port: 3000
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 60
    periodSeconds: 60
  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 30

config:
  springProfilesActive: production
  logLevel: INFO
  frontendUserApiUrl: http://localhost:8081
  frontendRecipeApiUrl: http://localhost:8082
  frontendInteractionApiUrl: http://localhost:8083
  frontendCategoryApiUrl: http://localhost:8084

secrets:
  jwtSecret: {{JWT_SECRET}} 