@startuml
entity User {
  *id : UUID
  sub : String
  email : String
  image : String
  bio : String
  social : String
  authProvider : String
}
entity Recipe {
  *id : UUID
  recipeName : String
  cuisine : String
  prepTime : Int
  serving : Int
  description : String
  images : String
  ingredients : Text // or JSON
  steps : Text // or JSON
  calories : Float
  nutritionJson : Text // Nutritionix API response
  owner : UUID
  categoryID : UUID
  isArchived : Boolean
}
entity Comment {
  *id : UUID
  recipeID : UUID
  userID : UUID
  content : String
  createdAt : DateTime
}
entity Category {
  *id : UUID
  name : String
}
entity Like {
  *id : UUID
  userID : UUID
  recipeID : UUID
  createdAt : DateTime
}
entity RecipeReport {
  *id : UUID
  recipeID : UUID
  reporterUserID : UUID
  reason : String
  status : String
  createdAt : DateTime
}
entity UserReport {
  *id : UUID
  reportedUserID : UUID
  reporterUserID : UUID
  reason : String
  status : String
  createdAt : DateTime
}
User ||--o{ Recipe : owns
User ||--o{ Comment : writes
User ||--o{ Like : likes
User ||--o{ RecipeReport : reports
User ||--o{ UserReport : reports
Recipe ||--o{ Comment : has
Recipe ||--o{ Like : liked
Recipe ||--o{ RecipeReport : reported
Recipe }o--|| Category : categorized
UserReport }o--|| User : reported
@enduml 