@startuml
actor User
actor Visitor

User --> (Browse/Search Recipes)
User --> (Like Recipe)
User --> (Comment on Recipe)
User --> (Delete Comment)
User --> (See Calories for Recipe)
User --> (View Recipe Details)
User --> (View Own Recipes)
User --> (View Liked Recipes)
User --> (View Popular/Recent Recipes)
User --> (View Categories)
Visitor --> (Browse Recipes)
@enduml 